name: "Check eval"
on:
  pull_request:
    paths:
      - 'flake.*'
      - 'ci.nix'
      - 'pkgs/**'
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Install nix
      uses: cachix/install-nix-action@V27
      with:
        nix_path: "nixpkgs=channel:nixos-unstable"
        extra_nix_config: |
          experimental-features = nix-command flakes
          access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
    - name: Setup magic nix cache
      uses: DeterminateSystems/magic-nix-cache-action@main
    - name: Show nixpkgs version
      run: nix-instantiate --eval -E '(import <nixpkgs> {}).lib.version'
    - name: Install essential packages
      run: nix profile install nixpkgs#nix-eval-jobs nixpkgs#jq
    - name: Check evaluation
      env:
        NIXPKGS_ALLOW_UNFREE: 1
        NIXPKGS_ALLOW_UNSUPPORTED_SYSTEM: 1
      run: |
        nix-eval-jobs --option restrict-eval true --flake ".#packages.$(nix eval --raw --impure --expr builtins.currentSystem)" > eval.json
        if [[ $(jq '.|select(has("error"))|length>0' eval.json) == "true" ]]; then jq -r '.|select(has("error"))|.error' eval.json; exit 1; else echo "Eval successful!"; fi
